INSERT INTO kamus_bahasa (kata, arti, kategori, konteks) VALUES
("A’ta’", 'Tersedak', 'Verba', NULL),
('Accirvag', 'Makhluk', 'Noun', NULL),
('Adab', 'Adab', 'Konsep', 'Etika atau sopan santun'),
('Adeş', 'atas', 'Preposisi', 'Posisi atau hierarki'),
('Aga', 'tiang', 'Benda', 'Struktur penyangga'),
('Ahal', 'tengah', 'Kata Keterangan', 'Posisi pusat'),
('Ahri', 'pahlawan', 'Noun', 'Tokoh heroik'),
('Aḫruk', 'hukum', 'Konsep', 'Aturan, kesepakatan bersama atau antara 2 pihak yang mesti ditaati'),
('Ainan', 'disana', 'Kata Keterangan', 'Menunjuk lokasi jauh'),
('Akan', 'Banyak', 'Kata Sifat', 'Jumlah besar, banyak, tidak sedikit, Jumlah lebih dari 3'),
('Akno', 'jelek', 'Kata Sifat', NULL),
('Akra', 'kambing', 'Hewan', NULL),
('Akwakra', 'kaya', 'Kata Sifat', 'Kekayaan material atau status'),
('Alnatran', 'aplikasi', 'Teknologi', NULL),
('Altaya', 'kalung', 'Benda', 'Perhiasan leher'),
('Alza', 'Jasa', 'Konsep', 'Layanan atau pekerjaan, sesuatu yang dilakukan untuk orang lain'),
('Amaric', 'rumit', 'Kata Sifat', NULL),
('Anaŝu', 'situasi', 'Konsep', 'Keadaan atau kondisi'),
('Anarzitifra', 'memperbaiki', 'Verba', NULL),
('Aqal', 'Akal', 'Konsep', 'Pikiran atau kecerdasan'),
('Aqidah', 'Aqidah', 'Agama', 'Keyakinan dasar dalam Islam'),
('Aqruna', 'Memori/ingatan', 'Konsep', 'Kemampuan mengingat'),
('Aracra', 'Kaidah', 'Konsep', 'Aturan atau prinsip dasar'),
('Arkuḫa', 'pendapat', 'Konsep', 'Opini atau pandangan'),
('Artanral', 'Abadi (benar benar abadi)', 'Konsep', 'Keabadian mutlak'),
('Aşa', 'Gawat', 'Kata Sifat', 'Darurat atau bahaya'),
('Asayalik', 'otoritas', 'Konsep', 'Wewenang atau kekuasaan'),
('Aŝe', 'Akal', 'Konsep', 'Pikiran, hal yang memberi manusia kemampuan untuk berfikir'),
('Aŝeliz', 'heran', 'Emosi', 'Rasa kagum atau takjub'),
('Asḫiş', 'Sering', 'Kata Keterangan', 'Frekuensi tinggi'),
('Aşit', 'detail', 'Konsep', 'Hal-hal kecil atau spesifik'),
('Ata', 'Terang', 'Kata Sifat', 'Cahaya atau jelas, sifat dari cahaya'),
('Ataru', 'Bintang', 'Benda', 'Benda langit'),
('Atayu', 'Angin', 'Benda', 'Aliran udara'),
('Atra', 'Bagus', 'Kata Sifat', 'Baik atau indah'),
('Aukaya', 'Definisi', 'Konsep', 'Penjelasan makna'),
('Aval', 'tinggi', 'Kata Sifat', 'Ketinggian atau level'),
('Avara', 'Sifat', 'Konsep', 'Ciri atau karakteristik'),
('Avtira', 'Gemerlap', 'Kata Sifat', 'Bersinar atau berkilau'),
('Ayada', 'Cahaya', 'Benda', 'Sumber penerangan'),
('Ayara', 'Langit', 'Benda', 'Langit atau atmosfer'),
('Aybilruf', 'gpp', 'Ekspresi', 'Singkatan informal: "gak apa-apa", konteksnya dalam bahasa kucqit seperti tidak apa apa informal'),
('Aytar', 'Asli, original', 'Kata Sifat', 'Autentik atau aslinya'),
('Ayzufu', 'Hias, Menghias', 'Verba', NULL),
('Azab', 'azab', 'Agama', 'Siksa atau hukuman akhirat'),
('Bajli', 'ajak, mengajak', 'Verba', 'Mengundang atau meminta seseorang untuk Datang'),
('Bazit', 'menetap', 'Verba', 'Tinggal atau menetap, stay--saya tinggal di..., saya hidup di...'),
('Biḫal', 'Bagal', 'Hewan', 'Kuda silang antara kuda dan keledai'),
('Bit', 'tetap', 'Kata Sifat', 'Stabil atau tidak berubah'),
('Buhan', 'Perut', 'Benda', NULL),
('Buḫdak', 'kejedot', 'Verba', 'Tertabrak atau terbentur'),
('Bukşav', 'beberapa saat, sewaktu-waktu', 'Kata Keterangan', NULL),
('Buşurb', 'Serap, Menyerap', 'Verba', NULL),
('Buvaz', 'berapa kali', 'Kata Tanya', 'Frekuensi'),
('Caltac', 'Logistic', 'Konsep', 'Logistik atau rantai pasok'),
('Carba', 'Jelas, terlihat', 'Kata Sifat', NULL),
('Cartac', 'Cakup, mencakup', 'Verba', NULL),
('Casviha', 'oksigen', 'Benda', 'Elemen kimia vital'),
('Cidyawwa', 'ciri khas', 'Konsep', 'Ciri unik atau identitas khusus'),
('Cig̈aş', 'kasus', 'Konsep', 'Peristiwa atau kejadian'),
('Ciyada', 'berlian', 'Benda', 'Batu mulia'),
('Clamataz', 'komponen', 'Konsep', 'Bagian dari sistem'),
('Cocke', 'basah', 'Kata Sifat', NULL),
('Covde', 'dingin', 'Kata Sifat', 'Suhu rendah'),
('Coztev', 'kering', 'Kata Sifat', 'Tidak basah'),
('Cuik', 'kali/kait', 'Benda', 'Alat pengait atau penghitung'),
('Curaḫac', 'prinsip', 'Konsep', 'Dasar atau aturan utama'),
('Curubav', 'Nyata', 'Kata Sifat', 'Real atau konkret'),
('Dab', 'tanah', 'Benda', 'Permukaan bumi'),
('Daḫ', 'Batu', 'Benda', 'Batu atau bebatuan'),
('Daka', 'Bentuk', 'Konsep', 'Wujud atau struktur'),
('Dalta', 'Arah', 'Konsep', 'Orientasi atau tujuan'),
('Darir', 'hijau', 'Warna', NULL),
('Daza', 'Jelas', 'Kata Sifat', 'Terlihat atau mudah dipahami'),
('Dig̈ḫaz', 'aneh benar benar aneh', 'Kata Sifat', 'Sangat tidak biasa'),
('Ditwaḫi', 'Ekspresi', 'Konsep', 'Ungkapan wajah atau perasaan'),
('Div', 'Jiwa', 'Konsep', 'Esensi, ruh, atribut kehidupan'),
('Duar', 'Buruk', 'Kata Sifat', 'Negatif atau jelek'),
('Dujag', 'menghentak', 'Verba', 'Menabrak keras'),
('Duyyar', 'keburukan', 'Konsep', 'Hal buruk atau negatif'),
('Enayo', 'Takdir', 'Konsep', 'Nasib atau ketentuan'),
('Euqi', 'Rasa', 'Indera', 'Pengalaman lidah, Rasa yang dirasakan lidah, taste'),
('Falsafah', 'Filsafat', 'Konsep', 'Ilmu tentang kehidupan dan realitas'),
('Fanayu', 'Udara', 'Benda', 'Gas yang kita hirup'),
('Farav', 'Atap', 'Benda', 'Penutup bangunan'),
('Farujur', 'poros', 'Benda', 'Titik pusat atau sumbu'),
('Fey', 'Manis', 'Kata Sifat', 'Rasa manis'),
('Fiqh', 'Fiqih', 'Agama', 'Ilmu hukum Islam'),
('Fruş', 'keberuntungan', 'Konsep', 'Nasib baik yang terjadi spontan'),
('Fujuka', 'komet', 'Benda', 'Benda langit berekor'),
('Funapru', 'Balon udara', 'Benda', 'Pesawat udara ringan, Balon Udara standar Kucqit'),
('Fusaşa', 'masa, periode', 'Konsep', 'Rentang waktu'),
('Futfut', 'lucu', 'Kata Sifat', 'Menghibur atau menggelitik'),
('Futrac', 'rapat', 'Kata Sifat', 'Dekat atau padat, kondisi berdekatan tanpa adanya celah'),
('Gadag', 'Pikul, memikul', 'Verba', 'Membawa di pundak'),
('Galma', 'Panjang', 'Kata Sifat', 'Ukuran atau durasi'),
('G̈ara', 'minyak', 'Benda', 'Cairan pelumas atau bahan bakar'),
('Gari', 'keras', 'Kata Sifat', 'Kuat atau sulit ditembus'),
('Gavyina', 'Plastik', 'Benda', 'Material sintetis'),
('G̈egña', 'mirip', 'Kata Sifat', 'Menyerupai atau sejenis'),
('G̈igi', 'Gigi', 'Benda', 'Organ mulut untuk mengunyah'),
('Gilat', 'Doktrin', 'Konsep', 'Ajaran resmi atau keyakinan'),
('Girat', 'Tujuan/Maksud', 'Konsep', 'Intensi atau sasaran'),
('G̈olo', 'keledai', 'Hewan', NULL),
('Gudaḫu', 'Ajak, Mangajak', 'Verba', 'Mengundang atau meminta seseorang untuk ikut'),
('Ḫaḫi', 'tanda', 'Konsep', 'Simbol atau indikator'),
('Haka', 'pahit', 'Kata Sifat', 'Rasa tidak enak'),
('Ḫalitarva', 'organisasi', 'Konsep', 'Struktur kelompok atau institusi'),
('Halluq', 'Rasa', 'Emosi', 'Perasaan atau sensasi, rasa yang dirasakan oleh hati, feel'),
('Hamla', 'Bawah', 'Preposisi', 'Posisi rendah'),
('Hamlay', 'hujan', 'Benda', 'Air dari langit'),
('Hamrat', 'tema', 'Konsep', 'Topik atau fokus'),
('Hañara', 'festival', 'Konsep', 'Perayaan atau acara'),
('Hanli', 'Matahari', 'Benda', 'Bintang pusat tata surya'),
('Hanwa', 'sunset', 'Benda', 'Matahari terbenam'),
('Harajak', 'burung', 'Hewan', NULL),
('Harsakyazad', 'selamat dating', 'Ekspresi', 'Salam sambutan'),
('Ḫarudu', 'Timbang, menimbang', 'Verba', NULL),
('Haŝara', 'angin', 'Benda', 'Aliran udara'),
('Hataji', 'Lapar', 'Emosi', 'Kebutuhan makan'),
('Ḫataxara', 'akademi', 'Institusi', 'Lembaga pendidikan tinggi'),
('Haur', 'Baik', 'Kata Sifat', 'Positif atau bagus'),
('Ḫavac', 'kekuatan, power', 'Konsep', 'Energi atau kemampuan'),
('Hayyar', 'Kebaikan', 'Konsep', 'Hal positif atau moral'),
('Ḫiga', 'tulang', 'Benda', 'Struktur internal tubuh'),
('Ḫilḫa', 'Counter', 'Konsep', 'Penyeimbang atau lawan, kebalikan,'),
('Hilih', 'Putih', 'Warna', NULL),
('Hillarnuf', 'Luar Biasa', 'Kata Sifat', 'Sangat hebat'),
('Ḫiyliya', 'membayangkan', 'Verba', 'Membuat gambaran mental atas sesuatu'),
('Ḫşp', 'Kuah', 'Benda', 'Cairan makanan'),
('Ḫu', 'Luka', 'Benda', 'Cedera atau goresan'),
('Ḫualov', 'tempat', 'Konsep', 'Lokasi atau ruang'),
('Hudrui', 'Badai', 'Benda', 'Angin kencang + hujan'),
('Hulu', 'dasar', 'Konsep', 'Bagian paling bawah'),
('Humun', 'Tapi', 'Konjungsi', 'Penanda kontras'),
('Hunma', 'Padahal', 'Konjungsi', NULL),
('Ḫunvu', 'Samar', 'Kata Sifat', 'Tidak jelas atau kabur'),
('Husa', 'Kecuali', 'Konjungsi', 'Pengecualian'),
('Ḫusera', 'Ideal', 'Kata Sifat', 'Sempurna atau standar tertinggi'),
('Ḫutla', 'Tempat', 'Konsep', 'Lokasi atau area'),
('Huyi', 'Sakral, suci', 'Kata Sifat', 'Suci atau religius'),
('Huyruv', 'ungu', 'Warna', NULL),
('Ḫuzya', 'Cocok', 'Kata Sifat', 'Pas atau sesuai'),
('Iblis', 'iblis', 'Agama', NULL),
('Icu', 'kucing', 'Hewan', NULL),
('Iglan', 'Malam', 'Waktu', NULL),
('Igraña', 'langit malam', 'Benda', 'Langit saat gelap, langit di malam hari'),
('Igrar', 'Bulan (moon)', 'Benda', 'Satelit alami bumi'),
('Ihŝe', 'penasaran', 'Emosi', 'Ingin tahu'),
('Ikzuj', 'pajak', 'Konsep', 'Pungutan negara'),
('Ilmiyah', 'Ilmiah', 'Kata Sifat', 'Berdasarkan ilmu pengetahuan'),
('Iñi', 'imut', 'Kata Sifat', 'Lucu atau menggemaskan'),
('Inli', 'Chair', 'Benda', 'Kursi'),
('Inriktip', 'Enskripsi', 'Teknologi', 'Proses penyandian data'),
('Iriva', 'model', 'Konsep', 'Contoh atau representasi'),
('Irzal', 'Simbol', 'Konsep', 'Tanda atau lambang'),
('Itlata', 'focus', 'Konsep', 'Konsentrasi atau perhatian'),
('Ittic', 'Pesan', 'Konsep', 'Informasi atau komunikasi'),
('Ivra', 'Jari', 'Benda', 'Bagian tangan'),
('Iylaya', 'keluarga', 'Konsep', 'Kelompok kerabat'),
('Izişi', 'pengaruh', 'Konsep', 'Dampak atau efek'),
('Izraza', 'contoh', 'Konsep', 'Ilustrasi atau kasus, penggambaran dari suatu hal'),
('Jalya', 'langsung, directly', 'Kata Keterangan', NULL),
('Jannah', 'Surga', 'Agama', 'Tempat bahagia setelah mati'),
('Jap', 'terus', 'Kata Keterangan', 'Terus-menerus'),
('Java', 'Stabil', 'Kata Sifat', 'Tidak goyah atau tetap'),
('Jicava', 'mengikuti', 'Verba', NULL),
('Jijar', 'bekas', 'Konsep', 'Jejak atau sisa'),
('Jiliyar', 'segera', 'Kata Keterangan', 'Cepat atau sekarang'),
('Jiyac', 'Luar', 'Preposisi', 'Di luar atau eksternal'),
('Jriva', 'khusus', 'Kata Sifat', 'Spesifik atau eksklusif'),
('Kadme', 'Makna/maksud', 'Konsep', 'Tujuan atau arti'),
('Kaḫ', 'dalam, di dalam', 'Preposisi', 'Di dalam ruang atau konteks'),
('Kaio', 'Upaya', 'Konsep', 'Usaha atau kerja keras'),
('Kakukav', 'Rapat kerja', 'Konsep', 'Pertemuan formal'),
('Kalri', 'Emas', 'Benda', NULL),
('Kaq', 'Sama', 'Kata Sifat', 'Identik atau serupa'),
('Kaqazan', 'Sinonim', 'Konsep', 'Kata dengan arti sama'),
('Karav', 'elang', 'Hewan', NULL),
('Karda', 'Ayah', 'Orang', 'Orang tua laki-laki'),
('Karna', 'siang', 'Waktu', NULL),
('Karpten', 'tunduk', 'Verba', 'Menyerah atau patuh'),
('Kasşwa', 'asli, original', 'Kata Sifat', 'Autentik'),
('Katña', 'bangga', 'Emosi', 'Rasa percaya diri'),
('Kav', 'Bahkan', 'Konjungsi', 'Penekanan tambahan'),
('Kayiya', 'seimbang', 'Kata Sifat', 'Proporsional atau stabil'),
('Kaza', 'Abang (lk)', 'Orang', 'Saudara laki-laki yang lebih tua'),
('Kede', 'Rakus', 'Kata Sifat', 'Serakah atau tamak'),
('Kernekta', 'Samudera', 'Benda', 'Laut luas'),
('Kerta', 'Maroon', 'Warna', 'Merah tua'),
('Kima', 'pen', 'Benda', 'Alat tulis'),
('Kinji', 'Anjing', 'Hewan', NULL),
('Kira', 'Besar', 'Kata Sifat', 'Ukuran atau skala'),
('Kiral', 'Kunci', 'Benda', 'Alat pembuka'),
('Kirka', 'angin topan', 'Benda', 'Angin kencang dahsyat'),
('Kirray', 'notebook; book for writing or make note', 'Benda', 'Buku catatan'),
('Kirtan', 'surat', 'Benda', 'Surat atau korespondensi'),
('Kisa', 'pintar', 'Kata Sifat', 'Cerdas atau cerdik'),
('Kitbi', 'book', 'Benda', 'Buku'),
('Klaşav', 'bank', 'Institusi', 'Lembaga keuangan'),
('Klimla', 'waris', 'Konsep', 'Penerima harta'),
('Klular', 'berharga', 'Kata Sifat', 'Bernilai tinggi'),
('Kohin', 'dungu', 'Kata Sifat', 'Bodoh atau tidak pintar'),
('Koknat', 'Blokir, memblokir', 'Verba', NULL),
('Kracu', 'kenyang', 'Emosi', 'Tidak lapar lagi'),
('Krasañ', 'brother', 'Orang', 'Saudara laki-laki'),
('Ku’za', 'Izin', 'Konsep', 'Persetujuan atau izin'),
('Kualra', 'Harta', 'Konsep', 'Kekayaan atau milik'),
('Kukan', 'Book; Usually big-sized book; big-sized scientific research or encyclopedia', 'Benda', 'Buku besar atau ensiklopedia'),
('Kuna', 'Data', 'Konsep', 'Informasi yang tersimpan '),
('Kurkar', 'Pelajaran', 'Konsep', 'Pelajaran atau pembelajaran'),
('Kurşava', 'insurance;', 'Konsep', 'Asuransi atau perlindungan'),
('Kussag̈a', 'menyerahkan', 'Verba', NULL),
('Kuwaka', 'ayam', 'Hewan', NULL),
('Kuyri', 'Masa lalu', 'Waktu', 'Waktu sebelum sekarang'),
('Kuzilimla', 'Mewarisi', 'Verba', NULL),
('Laciran', 'Tiram', 'Hewan', NULL),
('Lakan', 'Abadi (hanya di dunia saja)', 'Konsep', 'Keabadian sementara'),
('Lakra', 'setia', 'Kata Sifat', 'Loyal atau taat'),
('Larnuf', 'Biasa', 'Kata Sifat', 'Normal atau umum'),
('Lay', 'Air', 'Benda', 'Cairan vital'),
('Laycada', 'Mutiara', 'Benda', 'Batuan berharga dari laut'),
('Layciş', 'keringat', 'Benda', 'Cairan tubuh saat panas'),
('Layob', 'Air Mata', 'Benda', 'Cairan emosional dari mata'),
('Liḫuteravlo', 'Perpustakaan', 'Institusi', 'Tempat penyimpanan buku'),
('Limbi', 'disini', 'Kata Keterangan', 'Lokasi dekat'),
('Lipi', 'poin', 'Konsep', 'Poin atau angka'),
('Lipro', 'Noda', 'Benda', 'Noda atau bercak'),
('Liravj', 'Umum', 'Kata Sifat', 'Umum atau publik'),
('Liriar', 'Migration', 'Konsep', 'Perpindahan tempat'),
('Lita', 'Cacing', 'Hewan', NULL),
('Majduti', 'Skeptis', 'Kata Sifat', 'Ragu atau tidak percaya'),
('Makta', 'Pink', 'Warna', NULL),
('Malat', 'Teman', 'Orang', 'Sahabat atau rekan'),
('Manfra', 'Impossible/mustahil', 'Kata Sifat', 'Tidak mungkin'),
('Mareji', 'sadar', 'Emosi', 'Mengerti atau waspada'),
('Maŝara', 'akhir', 'Konsep', 'Penutup atau ujung'),
('Masşem', 'tuli', 'Kata Sifat', 'Tidak bisa mendengar'),
('Maŝva', 'sia-sia', 'Kata Sifat', 'Tidak berguna'),
('Matkan', 'Invisible, gk keliatan', 'Kata Sifat', 'Tidak terlihat'),
('Matli', 'Bersama', 'Preposisi', 'Dengan atau bersama-sama'),
('Mayanna', 'keberuntungan', 'Konsep', 'Nasib baik'),
('Mayatar', 'pulau', 'Benda', 'Daratan di tengah laut'),
('Maz', 'Tanpa', 'Preposisi', 'Tidak memiliki'),
('Mirila', 'biru', 'Warna', NULL),
('Mirm', 'Sunyi', 'Kata Sifat', 'Tenang atau diam'),
('Mirmarac', 'Rahasia', 'Konsep', 'Hal yang disembunyikan'),
('Mivyaras', 'Logistic', 'Konsep', 'Rantai pasok atau distribusi'),
('Mudru', 'Belakang', 'Preposisi', 'Di belakang'),
('Mudturur', 'Stagnan', 'Kata Sifat', 'Tidak berkembang'),
('Mug̈uru', 'gundah', 'Emosi', 'Resah atau gelisah'),
('Muḫa', 'kuat', 'Kata Sifat', 'Keras atau berdaya'),
('Mumnu', 'Siput', 'Hewan', NULL),
('Munki', 'alasan', 'Konsep', 'Sebab atau motif'),
('Murava', 'mengandung (berisi)', 'Verba', 'Memiliki atau menyimpan'),
('Mutraḫ', 'Ahli', 'Kata Sifat', 'Pakar atau profesional'),
('Muyaŝ', 'contoh', 'Konsep', 'Ilustrasi atau kasus'),
('Muyu', 'Halus', 'Kata Sifat', 'Lembut atau halus'),
('Nacva', 'bintang', 'Benda', 'Benda langit'),
('Nadda', 'panduan', 'Konsep', 'Petunjuk atau arahan'),
('Nafra', 'Possible', 'Kata Sifat', 'Mungkin atau bisa'),
('Nagov', 'Kabut', 'Benda', 'Uap air di udara'),
('Nakraz', 'Buta', 'Kata Sifat', 'Tidak bisa melihat'),
('Naksoyra', 'Sore', 'Waktu', NULL),
('Nalunarti', 'Relatif', 'Kata Sifat', 'Bergantung pada konteks'),
('Namlikya', 'Ilmiah', 'Kata Sifat', 'Berdasarkan ilmu'),
('Nan', 'di', 'Preposisi', 'Lokasi atau posisi'),
('Napsov', 'senjata', 'Benda', 'Alat pertahanan atau serangan'),
('Nar', 'Neraka', 'Agama', 'Tempat siksa akhirat'),
('Ñarafa', 'Kesempatan', 'Konsep', 'Peluang atau momen'),
('Narat', 'Judul', 'Konsep', 'Nama atau kepala'),
('Ñaşa', 'Langit pagi', 'Benda', 'Langit saat pagi'),
('Nem', 'Iklan', 'Konsep', 'Promosi atau periklanan'),
('Niḫanav', 'semu', 'Kata Sifat', 'Tidak nyata atau palsu'),
('Nihha', 'sembunyi', 'Verba', 'Menyembunyikan diri'),
('Nihhiftu', 'Azali', 'Konsep', 'Abadi sejak awal'),
('Nihri', 'Sunrise', 'Benda', 'Matahari terbit'),
('Niku', 'adik (pr)', 'Orang', 'Saudara perempuan'),
('Nilasi', 'Manusia', 'Orang', 'Makhluk rasional'),
('Ñivari', 'Metode', 'Konsep', 'Cara atau prosedur'),
('Nizihha', 'menyembunyikan', 'Verba', NULL),
('Ñolev', 'Coklat', 'Warna', NULL),
('Nuddu', 'Menit', 'Waktu', NULL),
('Nuñat', 'menghindar', 'Verba', 'Menjauhi atau mengelak'),
('Nuyravwi', 'Layak', 'Kata Sifat', 'Patut atau pantas'),
('Nwahu', 'Masalah', 'Konsep', 'Kendala atau isu'),
('Olik', 'Berat', 'Kata Sifat', 'Massa tinggi atau sulit'),
('Onov', 'Babi', 'Hewan', NULL),
('Oyoka', 'Bebek', 'Hewan', NULL),
('Petega', 'plin-plan', 'Kata Sifat', 'Tidak konsisten'),
('Piruta', 'Cecer, Mencecer', 'Verba', 'Menyebar atau berserakan'),
('Pişvu', 'krem', 'Warna', NULL),
('Pudga', 'Pijat, memijat', 'Verba', NULL),
('Puñu', 'Kenyal', 'Kata Sifat', NULL),
('Puşaş', 'Jerawat', 'Benda', 'Masalah kulit'),
('Qañ', 'Juga', 'Konjungsi', 'Penambahan'),
('Qanag', 'besi', 'Benda', 'Logam'),
('Qiraji', 'membiarkan', 'Verba', 'Mengizinkan atau melepaskan'),
('Qirev', 'ukir, Mengukir', 'Verba', NULL),
('Qirinaḫ', 'ide', 'Konsep', 'Gagasan atau pemikiran'),
('Qracu', 'mengupas', 'Verba', 'Melepas kulit'),
('Que', 'Jauh', 'Kata Sifat', 'Jarak jauh'),
('Qutu', 'Pendek', 'Kata Sifat', 'Panjang rendah'),
('Racatin', 'Rumput', 'Benda', 'Tumbuhan rendah'),
('Raḫ', 'bendera', 'Benda', 'Lambang atau simbol'),
('Raḫḫo', 'tamu', 'Orang', 'Pengunjung'),
('Raḫlik', 'pemimpin', 'Orang', 'Penguasa atau ketua'),
('Rakuta', 'Laut', 'Benda', 'Samudera atau lautan'),
('Ralana', 'Pajang, Memajang', 'Verba', 'Menampilkan'),
('Raltam', 'Guru', 'Orang', 'Pendidik'),
('Ranaḫ', 'Jelas', 'Kata Sifat', 'Terlihat atau mudah dipahami'),
('Rasage', 'benua', 'Benda', 'Daratan besar'),
('Rasu', 'lubang', 'Benda', 'Celah atau lubang'),
('Ratta', 'atap/genteng', 'Benda', 'Penutup bangunan'),
('Ratta', 'Sinyal', 'Konsep', 'Isyarat atau tanda'),
('Razub', 'seram', 'Kata Sifat', 'Menakutkan'),
('Razzihal', 'paru-paru', 'Benda', 'Organ pernapasan'),
('Re', 'Tentang', 'Preposisi', 'Mengenai atau berkaitan'),
('Rejlin', 'kekal', 'Kata Sifat', 'Abadi atau permanen'),
('Rekna', 'Merah', 'Warna', NULL),
('Rifjir', 'Ringkas', 'Kata Sifat', 'Singkat atau padat'),
('Rig̈aḫ', 'terbalik', 'Kata Sifat', 'Berlawanan atau terbalik'),
('Rig̈ua', 'Bintang', 'Benda', 'Benda langit'),
('Riji', 'Tikus', 'Hewan', NULL),
('Rikka', 'Indera', 'Konsep', 'Pancaindra'),
('Rimmiña', 'nilai', 'Konsep', 'Harga atau bobot'),
('Riŝuru', 'Lumayan', 'Kata Sifat', 'Cukup baik'),
('Rithala', 'gerimis', 'Benda', 'Hujan ringan'),
('Ritif', 'Sedikit', 'Kata Sifat', 'Jumlah kecil'),
('Rivya', 'Kupu-kupu', 'Hewan', NULL),
('Riwaşa', 'Jarang', 'Kata Sifat', 'Tidak sering'),
('Rojo', 'kotor', 'Kata Sifat', 'Tidak bersih'),
('Ronaven', 'berhutang', 'Verba', NULL),
('Rowen', 'HUtang', 'Konsep', 'Kewajiban finansial'),
('Rudan', 'Jam (hour)', 'Waktu', NULL),
('Rufrahun', 'Relatif', 'Kata Sifat', 'Bergantung pada sudut pandang'),
('Rug̈ka', 'kaki', 'Benda', 'Anggota tubuh'),
('Rugva', 'Gaya/style', 'Konsep', 'Model atau gaya'),
('Ruh', 'ruh', 'Konsep', 'Jiwa atau esensi'),
('Ruknu', 'rukun', 'Konsep', 'Dasar atau pilar'),
('Ruraya', 'mengira', 'Verba', 'Menganggap atau berpendapat'),
('Rurwa', 'Kadang', 'Kata Keterangan', 'Terkadang'),
('Ruşab', 'usus', 'Benda', 'Saluran pencernaan'),
('Ruşala', 'Tipe', 'Konsep', 'Jenis atau kategori'),
('Ruttaj', 'diantara', 'Preposisi', 'Di tengah'),
('Ruvva', 'hutan', 'Benda', 'Area berpohon'),
('Ruzihudun', 'Intrepretation', 'Konsep', 'Penafsiran'),
('Ruzuq', 'Masalah', 'Konsep', 'Kendala atau kesulitan'),
('Ruzyat', 'berita', 'Konsep', 'Informasi terbaru'),
('Ryalu', 'alas/karpet', 'Benda', 'Penutup lantai'),
('Sa', 'dengan', 'Preposisi', 'Menggunakan atau bersama'),
('Şac', 'Asin', 'Kata Sifat', 'Rasa garam'),
('Sacara', 'Sistem', 'Konsep', 'Struktur atau metode'),
('Sacram', 'rumus', 'Konsep', 'Persamaan atau aturan'),
('Şafa’at', 'Syafa’at', 'Agama', 'Interseksi atau pertolongan'),
('Ŝahhaş', 'padam, memadamkan', 'Verba', NULL),
('Sajara', 'Konsep', 'Konsep', 'Ide atau gagasan'),
('Salata', 'Kakak (pr)', 'Orang', 'Saudara perempuan'),
('Saqra', 'depan', 'Preposisi', 'Di muka'),
('Şarat', 'Syarat', 'Konsep', 'Kondisi atau persyaratan'),
('Satac', 'payah', 'Kata Sifat', 'Lemah atau tidak kuat'),
('Ŝavca', 'Kota', 'Benda', 'Wilayah urban'),
('Savo', 'hangus', 'Kata Sifat', 'Terbakar atau rusak'),
('Savuryi', 'Bijaksana', 'Kata Sifat', 'Cerdas dan bijak'),
('Şawa', 'asal', 'Konsep', 'Asal-usul atau sumber'),
('Şay', 'abu-abu', 'Warna', NULL),
('Şaytan', 'setan', 'Agama', 'Makhluk jahat'),
('Ŝe', 'atau', 'Konjungsi', 'Pilihan'),
('Ŝeḫac', 'Otak', 'Benda', 'Organ berpikir'),
('Şerv', 'Gelap', 'Kata Sifat', 'Tidak ada cahaya'),
('Şeva', 'pola', 'Konsep', 'Desain atau repetisi'),
('Şeya', 'Gurih', 'Kata Sifat', 'Rasa sedap'),
('Şicar', 'garam', 'Benda', 'Mineral penyedap'),
('Şiḫayaxa', 'antique', 'Kata Sifat', 'Antik atau kuno'),
('Şill', 'isi', 'Konsep', 'Isi atau konten'),
('Simutkan', 'Software', 'Teknologi', 'Program komputer'),
('Sin', 'dari', 'Preposisi', 'Asal atau sumber'),
('Şiri', 'biru dongker', 'Warna', NULL),
('Şiru', 'ibu', 'Orang', 'Orang tua perempuan'),
('Ŝiŝ', 'Ular', 'Hewan', NULL),
('Şitaru', 'miskin', 'Kata Sifat', 'Tidak punya harta'),
('Sitig̈ḫa', 'kerak', 'Benda', 'Endapan atau lapisan keras'),
('Sitilog̈', 'kepeleset', 'Verba', 'Terpeleset atau tergelincir'),
('Şivacra', 'Inovasi', 'Konsep', 'Penemuan baru'),
('Şivir', 'Kaca', 'Benda', 'Material transparan'),
('Şizaka', 'kayu', 'Benda', 'Material dari pohon'),
('Solih', 'Shaleh', 'Kata Sifat', 'Saleh atau baik hati'),
('Sora', 'Jingga', 'Warna', NULL),
('Sovt', 'alat', 'Benda', 'Perangkat atau instrumen'),
('Sracavi', 'bingung?', 'Emosi', 'Tidak paham atau ragu'),
('Ŝsawagra', 'Ombak', 'Benda', 'Gelombang laut'),
('Şta', 'kecil', 'Kata Sifat', 'Ukuran kecil'),
('Subuh', 'Shubuh', 'Waktu', 'Waktu antara matahari terbit'),
('Şuku', 'sikat', 'Benda', 'Alat pembersih'),
('Şulu', 'sapu', 'Benda', 'Alat membersihkan lantai'),
('Şulu', 'Tajam', 'Kata Sifat', 'Runcing atau menusuk'),
('Şuraku', 'danau', 'Benda', 'Cekungan berisi air'),
('Suralav', 'peta', 'Benda', 'Gambar wilayah'),
('Şuruv', 'gunting', 'Benda', 'Alat potong'),
('Şurzyaw', 'sumber', 'Konsep', 'Asal atau penyedia'),
('Şuyri', 'pedang', 'Benda', 'Senjata tajam'),
('Ŝuzihhu', 'menghembuskan', 'Verba', 'Mengeluarkan napas'),
('Tacnan', 'Kritik, Mengkritik', 'Verba', NULL),
('Tagaña', 'Jangkau, menjangkau', 'Verba', NULL),
('Takit', 'Kelinci', 'Hewan', NULL),
('Takku', 'Target', 'Konsep', 'Tujuan atau sasaran'),
('Takruf', 'Cacat', 'Kata Sifat', 'Tidak sempurna'),
('Taksa', 'detik', 'Waktu', NULL),
('Tala', 'Juga', 'Konjungsi', 'Penambahan'),
('Talyan', 'Muda', 'Kata Sifat', 'Belum tua'),
('Tanayar', 'Bersantai', 'Verba', 'Rehat atau santai'),
('Taqdir', 'Takdir', 'Konsep', 'Nasib atau ketentuan'),
('Tarignaş', 'Mengumpulkan', 'Verba', NULL),
('Tayaşirta', 'deskripsi', 'Konsep', 'Penjelasan rinci'),
('Tayr', 'santai', 'Kata Sifat', 'Tidak tegang'),
('Taytar', 'Sektor', 'Konsep', 'Bidang atau divisi'),
('Tazkac', 'menyerahkan', 'Verba', NULL),
('Tera', 'Tempat/Posisi', 'Konsep', 'Lokasi atau titik'),
('Tervax̂a', 'divisi', 'Konsep', 'Bagian atau departemen'),
('Tex̂evu', 'Pikul, memikul', 'Verba', NULL),
('Tey', 'Asam', 'Kata Sifat', 'Rasa asam'),
('Tivaña', 'kondisi', 'Konsep', 'Keadaan atau situasi'),
('Tivtira', 'ar. Istilah', 'Konsep', 'Istilah Arab'),
('Tlig̈', 'bel', 'Benda', 'Alat bunyi'),
('Tobmu', 'Pagi', 'Waktu', NULL),
('Todrag̈', 'Lonceng', 'Benda', 'Alat bunyi'),
('Trukan', 'Hampa', 'Kata Sifat', 'Kosong atau tidak berisi'),
('Tubat', 'Ulat Bulu', 'Hewan', NULL),
('Tukka', 'Jeda', 'Konsep', 'Pause atau istirahat'),
('Tuknu', 'aneh', 'Kata Sifat', 'Tidak biasa'),
('Tumu', 'ikan', 'Hewan', NULL),
('Tunvu', 'warna', 'Konsep', 'Spektrum visual'),
('Turdun', 'Jagung', 'Benda', 'Tanaman pangan'),
('Tuşamat', 'ragu', 'Emosi', 'Tidak yakin'),
('Tusuflu', 'Keluh, mengeluh', 'Verba', NULL),
('Tuşut', 'ujung', 'Konsep', 'Akhir atau puncak'),
('Tutan', 'Kertas', 'Benda', 'Material tulis'),
('Tuz', 'akhir', 'Konsep', 'Penutup, masa dimana suatu hal habis'),
('Tyurua', 'Terma, lema', 'Konsep', 'Istilah atau kata dasar'),
('Uizar', 'Sulit', 'Kata Sifat', 'Tidak mudah'),
('Uktyav', 'Populer', 'Kata Sifat', 'Terkenal, diketahui banyak orang'),
('Ulşut', 'inti', 'Konsep', 'Pusat atau pokok'),
('Ulyun', 'Besok', 'Waktu', NULL),
('Unqut', 'Kdang', 'Kata Keterangan', 'Kadang-kadang'),
('Unu', 'Tumpul', 'Kata Sifat', 'Tidak tajam'),
('Uqa', 'Jantung', 'Benda', 'Organ vital'),
('Uraku', 'Sungai', 'Benda', 'Aliran air yang mengarah'),
('Urru', 'Rajin', 'Kata Sifat', 'Giat atau tekun'),
('Urt', 'New', 'Kata Sifat', 'Baru'),
('Urtul', 'Lama', 'Kata Sifat', 'Tua atau lama, Kebalikan dari baru'),
('Urum', 'Sapi', 'Hewan', NULL),
('Uyava', 'bijak', 'Kata Sifat', 'Cerdas dan arif'),
('Uzir', 'Mudah', 'Kata Sifat', 'Tidak sulit'),
('Va', 'ke', 'Preposisi', 'Menuju atau arah'),
('Vagga', 'bahaya/berbahaya', 'Kata Sifat', 'Risiko atau ancaman'),
('Vaḫşev', 'Tua', 'Kata Sifat', 'Usia lanjut'),
('Vaḫuva', 'Taruh, Menaruh', 'Verba', NULL),
('Vakkac', 'canggih', 'Kata Sifat', 'Modern atau maju'),
('Valwa', 'bibit', 'Benda', 'Benih atau calon tanaman'),
('Valyun', 'kemarin', 'Waktu', NULL),
('Vaña', 'Langit', 'Benda', 'Atmosfer atau ruang atas'),
('Var', 'Dekat', 'Kata Sifat', 'Jarak pendek'),
('Varag', 'Raja', 'Orang', 'Pemimpin tertinggi'),
('Varud', 'Negara', 'Konsep', 'Wilayah berdaulat'),
('Vasa', 'Cerdas', 'Kata Sifat', 'Pintar atau cerdik'),
('Vatu', 'Sampai', 'Preposisi', 'Hingga atau sampai'),
('Vaya', 'Cinta', 'Emosi', 'Perasaan sayang'),
('Vig̈ara', 'Renung, merenung', 'Verba', NULL),
('Vili', 'Rendah', 'Kata Sifat', 'Tidak tinggi'),
('Viq', 'Rancu', 'Kata Sifat', 'Tidak jelas atau campur'),
('Virpax̂', 'Gurun', 'Benda', 'Daerah kering'),
('Visan', 'Bersih', 'Kata Sifat', 'Tidak kotor'),
('Vizege', 'bongkar, membongkar', 'Verba', NULL),
('Voln', 'Hitam', 'Warna', NULL),
('Voşq', 'fitnah', 'Konsep', 'Isu palsu atau tuduhan'),
('Vu', 'lalu, kemudian', 'Konjungsi', 'Urutan waktu'),
('Vugna', 'Asap', 'Benda', 'Gas hasil pembakaran'),
('Vuqqu', 'Lembah', 'Benda', 'Cekungan antar gunung'),
('Vuwa', 'Walaupun', 'Konjungsi', 'Meskipun'),
('Vyaya', 'Benda', 'Konsep', 'Objek atau materi'),
('Vzal', 'Sesuatu', 'Konsep', 'Entitas atau objek'),
('Wadri', 'Dunia', 'Konsep', 'Semesta atau bumi'),
('Wagra', 'gelombang', 'Benda', 'Gerakan berulang'),
('Warşa', 'Cara', 'Konsep', 'Metode atau prosedur'),
('Watta', 'hebat', 'Kata Sifat', 'Luas atau luar biasa'),
('Watuga', 'Serakah', 'Kata Sifat', 'Tamak atau rakus'),
('Wun', 'Syair', 'Konsep', 'Puisi atau puisi lama'),
('Wuzun', 'Hasil', 'Konsep', 'Hasil dari suatu proses'),
('Ya’ya', 'Sendiri', 'Kata Sifat', 'Sendiri'),
('Yaltix̂', 'energi', 'Konsep', 'Daya atau kekuatan'),
('Yankirf', 'kemampuan (ability)', 'Konsep', 'Kapasitas atau skill'),
('Yaruḫa', 'keliru', 'Kata Sifat', 'Salah atau tidak tepat'),
('Yataŝ', 'Ringan', 'Kata Sifat', 'Tidak berat'),
('Yatḫiḫa', 'mencoba', 'Verba', NULL),
('Yatne', 'Masa depan', 'Waktu', NULL),
('Yeşñe', 'Nilai', 'Konsep', 'Value, Nilai tak terhitung, "karena dia memiliki nilai-nilai yang tak dimiliki orang lain"'),
('Yig̈gi', 'kuning', 'Warna', NULL),
('Yoroḫa', 'sesat', 'Kata Sifat', 'Salah jalan atau salah arah'),
('Yug̈a', 'Botak', 'Kata Sifat', 'Tidak berambut'),
('Yula', 'Lembut', 'Kata Sifat', 'Halus atau empuk'),
('Yutya', 'seakan-akan', 'Kata Keterangan', 'Seperti atau mirip'),
('Za', 'bahwa', 'Konjungsi', 'Penanda klaim atau fakta'),
('Zaari', 'singa jantan', 'Hewan', NULL),
('Zaarum', 'Singa betina', 'Hewan', NULL),
('Zaca', 'Musuh', 'Orang', 'Lawan atau antagonis'),
('Zag̈', 'lain (other)', 'Kata Sifat', 'Berbeda atau lainnya'),
('Zaḫav', 'Ide', 'Konsep', 'Gagasan atau pikiran'),
('Zaḫdaq', 'kokoh', 'Kata Sifat', 'Kuat atau stabil'),
('Zakat', 'zakat', 'Agama', 'Wajib zakat dalam Islam'),
('Zala', 'adalah', 'Kata Kerja', 'Penyamaan atau identifikasi'),
('Zalyaf', 'Bumi', 'Benda', 'Planet tempat kita tinggal'),
('Zañara', 'penting', 'Kata Sifat', 'Signifikan atau vital'),
('Zañara', 'Sangka, menyangka', 'Verba', 'Mengira atau menduga'),
('Zanku', 'adik (lk)', 'Orang', 'Saudara laki-laki yang lebih muda'),
('Zaqlar', 'bodoh', 'Kata Sifat', 'Tidak pintar'),
('Zargan', 'Petir', 'Benda', 'Listrik alam'),
('Zarig̈', 'Kilat', 'Benda', 'Cahaya petir'),
('Zavx̂', 'Kadang', 'Kata Keterangan', 'Terkadang'),
('Zaw', 'Setiap/semua', 'Kata Sifat', 'Setiap atau semua dalam "Setiap makhluk di bumi" "semua yang hidup pasti mati'),
('Zaziz', 'memerintajkan', 'Verba', 'Memberi perintah'),
('Zeg̈ia', 'reflek', 'Konsep', 'Pantulan atau respons'),
('Zibat', 'sendok', 'Benda', 'Alat makan'),
('Zidaş', 'Unggul', 'Kata Sifat', 'Lebih baik atau superior'),
('Zig̈ḫav', 'Tebing', 'Benda', 'Lereng gunung seperti dinding terjal'),
('Zigris', 'Guruh', 'Benda', 'Suara petir'),
('Zihnag̈i', 'selamat tinggal', 'Ekspresi', 'Perpisahan'),
('Zikab', 'Serigala', 'Hewan', NULL),
('Ziñat', 'tentang, Menentang', 'Preposisi', 'Mengenai atau melawan'),
('Ziran', 'kuda', 'Hewan', NULL),
('Zirik', 'berisik', 'Kata Sifat', 'Bising atau ramai'),
('Zirkazan', 'antonym', 'Konsep', 'Lawan kata, kosakata yang memiliki arti berlawanan dengan kosakata asalnya'),
('Zivirp', 'debu', 'Benda', 'Partikel halus'),
('Ziya', 'seru', 'Kata Sifat', 'Menarik atau menyenangkan'),
('Zrañ', 'panas', 'Kata Sifat', 'Suhu tinggi'),
('Zrig̈', 'beda', 'Kata Sifat', 'Tidak sama'),
('Zuba', 'lalat', 'Hewan', NULL),
('Zukku', 'pohon', 'Benda', 'Tumbuhan besar'),
('Zuniş', 'haus', 'Emosi', 'Butuh minum'),
('Zursu', 'jurang', 'Benda', 'Lembah dalam'),
('Zusŝea', 'Emosi', 'Konsep', 'Perasaan atau afeksi'),
('Zuşu', 'nyamuk', 'Hewan', NULL),
('Zuvrapi', 'pasir', 'Benda', 'Butiran halus di pantai/desert'),
('Zwaqiḫ', 'selamanya', 'Kata Keterangan', 'Akan selalu ada, "Aku akan selalu disisimu selamanya"'); 

CREATE TABLE kamus_bahasa (
    id INT AUTO_INCREMENT PRIMARY KEY,
    kata VARCHAR(255) NOT NULL,
    arti TEXT NOT NULL,
    kategori VARCHAR(255),
    konteks TEXT
);